num1=input("Enter a number:")
num2=input("Enter another number:")
result1= float(num1)+float(num2)
result2=float(num1)*float(num2)
result3= float(num1)/float(num2)
result4=float(num1)%float(num2)
print(result1)
print(result2)
print(result3)
print(result4)